#Docker image from Docker Hub
image: mikk3lro/docker-phpunit-php7:7.2-phpunit6

options:
  #Minutes:
  max-time: 2

pipelines:
  #Executes on every push that do not match other rules
  default:
    - step:
        caches:
          - composer
        script:
          - curl -s https://mikk3lro.bitbucket.io/common-files/test_and_push_package.php?rand=$(shuf -i 1-1000 -n1) | php